// vue-element-admin/src/views/good/good-list.vue
<template>
  <div class="app-container">
    <el-row style="marginBottom: 20px;">
      <el-col :span="24">
        <el-input v-model="filter.name" placeholder="输入商品名称" style="width:140px;" />
        <CateSelect v-model='filter.cate' has-all style="width:120px;" />

        <el-select v-model="filter.check_status" placeholder="请选择状态" style="width:120px;">
          <el-option value=''>全部</el-option>
          <el-option
            v-for="(item) in checkStatusArr"
            :key="item.id"
            :label="item.label"
            :value="item.value"
          />
        </el-select>
        <el-date-picker
          v-model="filter.date"
          type="daterange"
          range-separator="至"
          style="width:220px;"
          start-placeholder="开始日期"
          end-placeholder="结束日期"
        />
      </el-col>
    </el-row>
    <el-row style="margin:25px 0;">
      <el-col :span='24'>
        <el-button type="primary" icon="el-icon-search" @click="filterHandle(1)">搜索</el-button>
        <el-button type="primary" icon="el-icon-delete" @click="filterHandle(4)">重置</el-button>
        <el-button type="primary" icon="el-icon-edit" @click="filterHandle(2)">添加</el-button>
        <el-button type="primary" icon="el-icon-download" @click="filterHandle(3)">导入</el-button>
      </el-col>
    </el-row>

    <!-- 表格 -->
    <el-table
      :data="list"
      style="width: 100%"
      border
    >
      <el-table-column fixed label="序号" prop="id" sortable="custom" align="center" width="80" type='index'>
        <!-- <template slot-scope="{row}">
          <span>{{ row._id }}</span>
        </template> -->
      </el-table-column>

      <el-table-column
        prop="name"
        label="商品"
        align='center'
      >
      <template slot-scope="{row}">
        <div class="good">
          <el-image :src='($img+row.img)' />
          <div v-text='row.name'></div>
        </div>
      </template>
      </el-table-column>

      <el-table-column
        prop="cate"
        label="品类"
        align='center'
      >
        <template slot-scope="{row}">
          <!-- 这里为什么不建议使用计算属性？ -->
          <div v-text='cate2Zh(row.cate)'></div>
        </template>
      </el-table-column>

      <el-table-column
        prop="hot"
        label="是否"
        align='center'
      >
        <template slot-scope="{row}">
          <div v-text='(row.hot?"是":"否")'></div>
        </template>
      </el-table-column>

      <el-table-column
        prop="price"
        label="价格"
        align='center'
      >
        <template slot-scope="{row}">
          <div>{{ row.price | rmb}}</div>
        </template>
      </el-table-column>

      <el-table-column
        prop="create_time"
        label="发布时间"
        align='center'
      >
        <template slot-scope="{row}">
          <div>{{ row.create_time | ymd }}</div>
        </template>
      </el-table-column>

      <el-table-column
        prop="store_status"
        label="状态"
        align='center'
      >
        <template slot-scope="{row}">
          <div>{{ row.store_status ? "已上架" : "未上架" }}</div>
        </template>
      </el-table-column>

      <el-table-column
        prop="check_status"
        label="审核状态"
        align='center'
      >
        <template slot-scope="{row}">
          <div>{{ checkStatus(row.check_status) }}</div>
        </template>
      </el-table-column>

      <el-table-column
        label="操作"
        align="center"
        width="200"
      >
        <template slot-scope="{row}">
          <el-button type="primary" size="mini" @click='rowHandle(3, row)' v-if='row.check_status===1'>{{row.store_status?'上架':'下架'}}</el-button>
          <el-button type="primary" size="mini" @click='rowHandle(1, row)'>编辑</el-button>
          <el-button type="danger" size="mini" @click='rowHandle(2, row)'>删除</el-button>
        </template>
      </el-table-column>

    </el-table>

    <!-- 参考作者封装的组件源码 -->
    <Pagination :total="total" :limit='filter.size' :pageSizes='[2,5,10,20]' @pagination='paginationChange'  />
  </div>
</template>

<script>
import Pagination from '@/components/Pagination'
import { fetchGoodList, fetchGoodDel } from '@/api/good'
import CateSelect from './components/CateSelect.vue'
import { mapState } from 'vuex'
export default {
  name: 'GoodList',
  components: { Pagination, CateSelect },
  data() {
    return {
      checkStatusArr: [
        { id: 1, value: 0, label: '待审核' },
        { id: 2, value: 1, label: '已审核成功' },
        { id: 3, value: -1, label: '审核失败' }
      ],
      // 查询的入参们（即后端接口要求的查询参数）
      filter: {
        name: '',
        cate: '',
        check_status: '',
        date: [],
        size: 10,
        page: 1
      },
      list: [],  // 商品列表
      total: 0,  // 用于分页
      count: 0,  // 计数器
    }
  },
  computed: {
    ...mapState('good', ['cates'])
  },
  watch: {
    count () {
      this.getList()
    }
  },
  created () {
    this.getList()
  },
  activated () {
    this.count++
  },
  methods: {
    getList () {
      const params = this.filter
      fetchGoodList(params).then(({ data })=>{
        console.log('----商品列表', data)
        this.list = data.list
        this.total = data.total
      })
    },
    filterHandle(idx) {
      if (idx === 1) {
        // 查询操作时，非分页的变化，都要把page重置为1
        this.filter.page = 1
        this.count++
      }
      if (idx === 2) {
        this.$router.push({ name: 'GoodAdd' })
      }
      if (idx === 3) {
        // this.downloadLoading = true
        import('@/vendor/Export2Excel').then(excel => {
          const tHeader = ['商品名称', '商品品类', '商品价格', '商品状态']

          const filterVal = ['name', 'cate', 'price', 'status']
          const data = this.formatJson(filterVal)

          excel.export_json_to_excel({
            header: tHeader,
            data,
            filename: 'qf-list'
          })
          // this.downloadLoading = false
        })
      }
    },
    //
    formatJson(filterVal) {
      // 表格数据
      return this.list.map(row => filterVal.map(k => {
        // 根据k进行若干数据处理
        // if (j === 'timestamp') {
        //   return parseTime(v[j])
        // } else {
        //   return v[j]
        // }
        return row[k]
      }))
    },
    // 处理品类
    cate2Zh (cate) {
      let result = ''
      if (this.cates) {
        const res = this.cates.find(ele=>ele.cate === cate)
        // console.log('---res', res)
        if (res) result = res.cate_zh
      }
      return result
    },
    // 监听分页器变化
    paginationChange ({ page, limit}) {
      // console.log('--- 分页变化了', ev)
      this.filter = { ...this.filter, page, size: limit }
      this.count++
    },
    rowHandle (idx, row) {
      if (idx === 1) {
        // 跳转编辑页
        this.$router.push(`/good/edit/${row._id}`)
      }
      if (idx === 2) {
        this.$confirm(`你确定要删除 ${row.name} 吗？`, {
          title: '危险'
        }).then(()=>{
          const ids = row._id
          fetchGoodDel(ids).then(()=>{
            if (this.list.length===1) {
              this.filter.page--
            }
            this.count++
          })
        })
      }
    }
  },
  beforeDestroy () {
    console.log('---good list des')
  }
}
</script>

<style lang="scss" scoped>
.good {
  .el-image {
    width: 60px;
    height: 60px;
  }
  text-align: center;
}
</style>

// react-webpack-admin/src/views/good/GoodList.jsx
import { useNavigate } from 'react-router-dom'
import { useEffect, useState, useMemo } from 'react'
import { useSelector } from 'react-redux'

import { Row, Col, Input, Select, DatePicker, Button, Tag, Space, Table, Tooltip, Image, Modal } from 'antd'
import { SettingOutlined, ExclamationCircleOutlined } from '@ant-design/icons'
import './style.scss'
import { useRequest } from 'ahooks'
import moment from 'moment'

import GoodSelect from './components/GoodSelect'
import { fetchGoodList, fetchGoodDel } from '@/api'
import Submit from '@/components/submit'

const { Option } = Select
const { RangePicker } = DatePicker
const { confirm } = Modal

// 导入Excel表：file-saver、xlsx
const formatJson = (filterVal, list) => {
  return list.map(v => filterVal.map(j => {
    if (j === 'hot') {
      return v[j] ? '是' : '否'
    }
    if (j==='create_time') {
      return moment(v[j]).format('YYYY年MM月DD日')
    }
    return v[j] // 不处理
  }))
}

// 在页面组件中调接口的一些小知识点
// 1、在useEffect中如何编写async/await代码？自己封装async函数并调用；使用useAsyncEffect来实现。
// 2、关注一下ahooks中的 useRequest(fetchAPI)
// 3、切忌：useEffect(async ()=>{})这样使用，不规范，会影响副作用的执行浏览。

export default () => {

  const navigate = useNavigate()  // navigate(-1/'/good/add', { replace: true })
  const { cates } = useSelector(state=>state.good)

  const [list, setList] = useState([])
  const [total, setTotal] = useState(0)
  const [date, setDate] = useState([])
  const [tableKeys, setTableKeys] = useState([])
  const [count, setCount] = useState(0)
  const [filter, setFilter] = useState({
    page: 1,
    size: 10,
    name: '',
    cate: ''
  })

  useEffect(()=>{
    fetchGoodList(filter).then(res=>{
      console.log('---商品列表', res)
      if (res.list) {
        setList(res.list)
        setTotal(res.total)
      }
    })
  }, [count])

  const columns = useMemo(()=>(
    [
      {
        title: '商品名称',
        dataIndex: 'name',
        align: 'center',
        key: 'name',
        // 自定义渲染单元格（*）
        render: (text, row, idx) => {
          // do something
          return (
            <div style={{textAlign:'center'}}>
              <Image src={CDN_URL+row.img} width={80} />
              <div>{ row.name }</div>
            </div>
          )
        }
      },
      {
        title: '商品价格',
        dataIndex: 'price',
        key: 'price',
        align: 'center',
        sorter: (a, b) => (a.price - b.price),
        render: (text) => <div>{`￥${text}`}</div>
      },
      {
        title: '商品品类',
        dataIndex: 'cate',
        key: 'cate',
        align: 'center',
        // 单元格渲染
        render: (text) => {
          let result = null
          if (cates.length > 0) {
            result = cates.find(ele=>ele.cate===text)
          }
          return result?.cate_zh
        }
      },
      {
        title: '是否热销',
        dataIndex: 'hot',
        key: 'hot',
        align: 'center',
        // 单元格渲染
        render: (text) => {
          return text ? '是' : '否'
        }
      },
      {
        title: '发布时间',
        dataIndex: 'create_time',
        key: 'create_time',
        align: 'center',
        // 单元格渲染
        render: (text) => {
          return moment(text).format('YYYY年MM月DD')
          // moment().format()  把时间戳转换成格式化字符
          // moment().valueOf()  把格式化字符串变成时间戳
        }
      },
      {
        title: '操作',
        key: 'handler',
        align: 'center',
        dataIndex: 'handler',
        render: (_, row) => (
          <>
            <Button type='primary'
              onClick={()=>{
                navigate('/good/edit/'+row._id)
              }}
            >编辑</Button>
            <Button
              danger
              disabled={tableKeys.length>0}
              style={{marginLeft:'10px'}}
              onClick={()=>{

                confirm({
                  title: `你确定要删除 ${row.name} 吗？`,
                  icon: <ExclamationCircleOutlined />,
                  onOk() {
                    const ids = row._id
                    fetchGoodDel(ids).then(()=>{
                      setCount(c=>c+1)
                    })
                  }
                });
              }}
            >删除</Button>
          </>
        ),
      }
    ]
  ), [cates, list, tableKeys])

  return (
    <div className='good-list'>
      <div className='filter'>
        <Row align='middle' >
          <Col span={2} style={{textAlign:'right'}}>商品名称：</Col>
          <Col span={4}>
            <Input
              placeholder='请输入商品名称'
              allowClear
              value={filter.name}
              onChange={ev=>setFilter(f=>({...f,name:ev.target.value}))}
            />
          </Col>
          <Col span={3} style={{textAlign:'right'}}>商品名称：</Col>
          <Col span={4}>
            <GoodSelect
              allowClear
              value={filter.cate}
              onChange={cate=>setFilter(f=>({...f,cate}))}
            />
          </Col>
          <Col span={3} style={{textAlign:'right'}}>日期搜索：</Col>
          <Col span={6}>
            <RangePicker value={date} onChange={ev=>{
              // antd时间选择器组件，取值结果是moment对象
              console.log('------时间选择器', ev[0].valueOf())
              console.log('------时间选择器', ev[1].format('YYYY-MM-DD'))
            }} />
          </Col>
        </Row>
        <Row align='middle' style={{marginTop:'20px'}}>
          <Col className='btns'>
            <Button type='primary' onClick={()=>{
              setFilter(f=>({...f, page:1}))
              setCount(c=>c+1)
            }}>查询</Button>
            <Button
              type='primary'
              onClick={()=>{
                setFilter(f=>({...f,name:'',cate:''}))
                setCount(c=>c+1)
              }}
            >重置</Button>
            <Button
              type='primary'
              onClick={()=>{
                // 动态导入语法（目前浏览器不支持）
                import('@/utils/Export2Excel').then(excel => {
                  // 设定Excel表头
                  const tHeader = ['商品名称', '价格', '品类', '是否热销', '发布时间']
                  const filterVal = ['name', 'price', 'cate', 'hot', 'create_time']

                  // 对Excel单元格中的数据进行格式化
                  const data = formatJson(filterVal, list)
                  console.log('---excel', excel)

                  excel.export_json_to_excel({
                    header: tHeader,  //  Excel表的表头
                    data,
                    filename: 'qf-good'
                  })
                })
              }}
            >导出</Button>
          </Col>
        </Row>
      </div>

      <div className='table'>
        <Table
          columns={columns}
          dataSource={list}
          rowKey='_id'
          title={()=>{
            // do something [render props]
            return (
              <Row >
                <Col span={2}>查询表格</Col>
                <Col span={8} offset={14} style={{textAlign:'right'}} className='header'>
                  <Button
                    type='primary'
                    onClick={
                      ()=>navigate('/good/add')
                    }>
                    新增
                  </Button>
                  <Tooltip title='列设置' placement='top'>
                    <SettingOutlined />
                  </Tooltip>

                </Col>
              </Row>
            )
          }}
          rowSelection={{
            // 在首列添加多选
            type: 'checkbox',
            onChange: (keys, rows) => {
              setTableKeys(keys)
            }
          }}
          pagination={{
            pageSizeOptions: [2,5,10,20],
            showSizeChanger: true,
            current: filter.page,
            pageSize: filter.size,
            total,
            showTotal: (t, r) => {
              // console.log('--t', t)
              // console.log('--r', r)
              return <div>{`第 ${r[0]}-${r[1]} 条/总共 ${t} 条`}</div>
            },
            onChange: (page, size) => {
              console.log('----A', page, size)
              setFilter(f=>({...f, page, size}))
              setCount(c=>c+1)
            },
            onShowSizeChange: (page, size) => {
              // console.log('----B', page, size)
              // setFilter(f=>({...f, size, page}))
              // setCount(c=>c+1)
            }
          }}
        />
      </div>
      <Submit>
        <Button
          danger
          disabled={tableKeys.length===0}
          onClick={()=>{
            console.log('---删除', tableKeys)
            confirm({
              title: '你确定要批量删除吗？',
              icon: <ExclamationCircleOutlined />,
              onOk() {
                const ids = tableKeys.reduce((prev, ele)=>(prev+=(';'+ele)), '')
                // console.log('---ids', ids)
                fetchGoodDel(ids).then(()=>{
                  setTableKeys([])
                  setCount(c=>c+1)
                })
              }
            });
          }}
        >
          批量删除
        </Button>
      </Submit>
    </div>
  )
}
